# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /MYPROJECTS/C_C++/ProjectCMake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /MYPROJECTS/C_C++/ProjectCMake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /MYPROJECTS/C_C++/ProjectCMake/CMakeFiles /MYPROJECTS/C_C++/ProjectCMake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /MYPROJECTS/C_C++/ProjectCMake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prog

# Build rule for target.
prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog
.PHONY : prog

# fast build rule for target.
prog/fast:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/build
.PHONY : prog/fast

sources/app/main.o: sources/app/main.c.o

.PHONY : sources/app/main.o

# target to build an object file
sources/app/main.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/app/main.c.o
.PHONY : sources/app/main.c.o

sources/app/main.i: sources/app/main.c.i

.PHONY : sources/app/main.i

# target to preprocess a source file
sources/app/main.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/app/main.c.i
.PHONY : sources/app/main.c.i

sources/app/main.s: sources/app/main.c.s

.PHONY : sources/app/main.s

# target to generate assembly for a file
sources/app/main.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/app/main.c.s
.PHONY : sources/app/main.c.s

sources/ericsonj/embedded/fft.o: sources/ericsonj/embedded/fft.c.o

.PHONY : sources/ericsonj/embedded/fft.o

# target to build an object file
sources/ericsonj/embedded/fft.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/ericsonj/embedded/fft.c.o
.PHONY : sources/ericsonj/embedded/fft.c.o

sources/ericsonj/embedded/fft.i: sources/ericsonj/embedded/fft.c.i

.PHONY : sources/ericsonj/embedded/fft.i

# target to preprocess a source file
sources/ericsonj/embedded/fft.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/ericsonj/embedded/fft.c.i
.PHONY : sources/ericsonj/embedded/fft.c.i

sources/ericsonj/embedded/fft.s: sources/ericsonj/embedded/fft.c.s

.PHONY : sources/ericsonj/embedded/fft.s

# target to generate assembly for a file
sources/ericsonj/embedded/fft.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/ericsonj/embedded/fft.c.s
.PHONY : sources/ericsonj/embedded/fft.c.s

sources/tools/tools.o: sources/tools/tools.c.o

.PHONY : sources/tools/tools.o

# target to build an object file
sources/tools/tools.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/tools.c.o
.PHONY : sources/tools/tools.c.o

sources/tools/tools.i: sources/tools/tools.c.i

.PHONY : sources/tools/tools.i

# target to preprocess a source file
sources/tools/tools.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/tools.c.i
.PHONY : sources/tools/tools.c.i

sources/tools/tools.s: sources/tools/tools.c.s

.PHONY : sources/tools/tools.s

# target to generate assembly for a file
sources/tools/tools.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/tools.c.s
.PHONY : sources/tools/tools.c.s

sources/tools/util.o: sources/tools/util.c.o

.PHONY : sources/tools/util.o

# target to build an object file
sources/tools/util.c.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/util.c.o
.PHONY : sources/tools/util.c.o

sources/tools/util.i: sources/tools/util.c.i

.PHONY : sources/tools/util.i

# target to preprocess a source file
sources/tools/util.c.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/util.c.i
.PHONY : sources/tools/util.c.i

sources/tools/util.s: sources/tools/util.c.s

.PHONY : sources/tools/util.s

# target to generate assembly for a file
sources/tools/util.c.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/sources/tools/util.c.s
.PHONY : sources/tools/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... prog"
	@echo "... sources/app/main.o"
	@echo "... sources/app/main.i"
	@echo "... sources/app/main.s"
	@echo "... sources/ericsonj/embedded/fft.o"
	@echo "... sources/ericsonj/embedded/fft.i"
	@echo "... sources/ericsonj/embedded/fft.s"
	@echo "... sources/tools/tools.o"
	@echo "... sources/tools/tools.i"
	@echo "... sources/tools/tools.s"
	@echo "... sources/tools/util.o"
	@echo "... sources/tools/util.i"
	@echo "... sources/tools/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

